apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---

apiVersion: v1
kind: Pod
metadata:
  name: sfia-task-frontend
  labels:
    app: sfia
spec:
  containers:
  - name: python-frontend
    image: ope079/python-frontend
    ports:
    - containerPort: 5000
---

apiVersion: v1
kind: Pod
metadata:
  name: sfia-task-backend1
  labels:
    app: sfia
spec:
  containers:
  - name: python-backend1
    image: ope079/python-backend1
    ports:
    - containerPort: 5001

---

apiVersion: v1
kind: Pod
metadata:
  name: sfia-task-backend2
  labels:
    app: sfia
spec:
  containers:
  - name: python-backend2
    image: ope079/python-backend2
    ports:
    - containerPort: 5002
---

apiVersion: v1
kind: Pod
metadata:
  name: sfia-task-backend3
  labels:
    app: sfia
spec:
  containers:
  - name: python-backend3
    image: ope079/python-backend3
    ports:
    - containerPort: 5003
